# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pb.basketballPB.base_pb2 as base_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='login.proto',
  package='com.proto',
  serialized_pb=_b('\n\x0blogin.proto\x12\tcom.proto\x1a\nbase.proto\"3\n\x08LoginReq\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61\x63\x63ount_pwd\x18\x02 \x01(\t\"\xcb\x03\n\x08LoginRes\x12\x0e\n\x03ret\x18\x01 \x01(\x11:\x01\x30\x12\x32\n\radministrator\x18\x02 \x01(\x0b\x32\x1b.com.proto.ManagerAccountPB\x12\x11\n\tui_switch\x18\x03 \x03(\t\x12,\n\x0bplayer_info\x18\x04 \x03(\x0b\x32\x17.com.proto.PlayerInfoPB\x12&\n\x08nba_team\x18\x05 \x03(\x0b\x32\x14.com.proto.NbaTeamPB\x12(\n\tjdbc_info\x18\x06 \x03(\x0b\x32\x15.com.proto.JdbcInfoPB\x12.\n\x0c\x63hannel_info\x18\x07 \x03(\x0b\x32\x18.com.proto.ChannelInfoPB\x12(\n\tdate_jdbc\x18\x08 \x03(\x0b\x32\x15.com.proto.JdbcInfoPB\x12\x1e\n\x16superstar_player_model\x18\t \x03(\x11\x12\x34\n\x0fmanager_account\x18\n \x03(\x0b\x32\x1b.com.proto.ManagerAccountPB\x12\'\n\x08sel_jdbc\x18\x0b \x01(\x0b\x32\x15.com.proto.JdbcInfoPB\x12\x0f\n\x07version\x18\x0c \x01(\x11\"C\n\rVerifyMailReq\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\x11\x12\x12\n\nlogin_type\x18\x03 \x01(\x11\"/\n\x10ManagerVersionPB\x12\n\n\x02id\x18\x01 \x01(\x11\x12\x0f\n\x07version\x18\x02 \x01(\tB\'\n\x18\x63om.manager.biz.protocolB\x0bLoginProtos')
  ,
  dependencies=[base_pb2.DESCRIPTOR, ])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOGINREQ = _descriptor.Descriptor(
  name='LoginReq',
  full_name='com.proto.LoginReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='com.proto.LoginReq.account_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_pwd', full_name='com.proto.LoginReq.account_pwd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=89,
)


_LOGINRES = _descriptor.Descriptor(
  name='LoginRes',
  full_name='com.proto.LoginRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='com.proto.LoginRes.ret', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='administrator', full_name='com.proto.LoginRes.administrator', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ui_switch', full_name='com.proto.LoginRes.ui_switch', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_info', full_name='com.proto.LoginRes.player_info', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nba_team', full_name='com.proto.LoginRes.nba_team', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jdbc_info', full_name='com.proto.LoginRes.jdbc_info', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel_info', full_name='com.proto.LoginRes.channel_info', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date_jdbc', full_name='com.proto.LoginRes.date_jdbc', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='superstar_player_model', full_name='com.proto.LoginRes.superstar_player_model', index=8,
      number=9, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='manager_account', full_name='com.proto.LoginRes.manager_account', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sel_jdbc', full_name='com.proto.LoginRes.sel_jdbc', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='com.proto.LoginRes.version', index=11,
      number=12, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=551,
)


_VERIFYMAILREQ = _descriptor.Descriptor(
  name='VerifyMailReq',
  full_name='com.proto.VerifyMailReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='com.proto.VerifyMailReq.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='language', full_name='com.proto.VerifyMailReq.language', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='login_type', full_name='com.proto.VerifyMailReq.login_type', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=620,
)


_MANAGERVERSIONPB = _descriptor.Descriptor(
  name='ManagerVersionPB',
  full_name='com.proto.ManagerVersionPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.proto.ManagerVersionPB.id', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='com.proto.ManagerVersionPB.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=622,
  serialized_end=669,
)

_LOGINRES.fields_by_name['administrator'].message_type = base_pb2._MANAGERACCOUNTPB
_LOGINRES.fields_by_name['player_info'].message_type = base_pb2._PLAYERINFOPB
_LOGINRES.fields_by_name['nba_team'].message_type = base_pb2._NBATEAMPB
_LOGINRES.fields_by_name['jdbc_info'].message_type = base_pb2._JDBCINFOPB
_LOGINRES.fields_by_name['channel_info'].message_type = base_pb2._CHANNELINFOPB
_LOGINRES.fields_by_name['date_jdbc'].message_type = base_pb2._JDBCINFOPB
_LOGINRES.fields_by_name['manager_account'].message_type = base_pb2._MANAGERACCOUNTPB
_LOGINRES.fields_by_name['sel_jdbc'].message_type = base_pb2._JDBCINFOPB
DESCRIPTOR.message_types_by_name['LoginReq'] = _LOGINREQ
DESCRIPTOR.message_types_by_name['LoginRes'] = _LOGINRES
DESCRIPTOR.message_types_by_name['VerifyMailReq'] = _VERIFYMAILREQ
DESCRIPTOR.message_types_by_name['ManagerVersionPB'] = _MANAGERVERSIONPB

LoginReq = _reflection.GeneratedProtocolMessageType('LoginReq', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQ,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:com.proto.LoginReq)
  ))
_sym_db.RegisterMessage(LoginReq)

LoginRes = _reflection.GeneratedProtocolMessageType('LoginRes', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRES,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:com.proto.LoginRes)
  ))
_sym_db.RegisterMessage(LoginRes)

VerifyMailReq = _reflection.GeneratedProtocolMessageType('VerifyMailReq', (_message.Message,), dict(
  DESCRIPTOR = _VERIFYMAILREQ,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:com.proto.VerifyMailReq)
  ))
_sym_db.RegisterMessage(VerifyMailReq)

ManagerVersionPB = _reflection.GeneratedProtocolMessageType('ManagerVersionPB', (_message.Message,), dict(
  DESCRIPTOR = _MANAGERVERSIONPB,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:com.proto.ManagerVersionPB)
  ))
_sym_db.RegisterMessage(ManagerVersionPB)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.manager.biz.protocolB\013LoginProtos'))
# @@protoc_insertion_point(module_scope)
