# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto.proto',
  package='',
  serialized_pb=_b('\n\x0bproto.proto\"Q\n\x11\x44\x61taComparisonRes\x12\x0e\n\x03ret\x18\x01 \x01(\x11:\x01\x30\x12\x1f\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x11.DataComparisonPB\x12\x0b\n\x03res\x18\x03 \x01(\t\"4\n\x10\x44\x61taComparisonPB\x12\x12\n\ntable_name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\t\":\n\x11\x44\x61taComparisonReq\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x12\n\ntable_name\x18\x02 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATACOMPARISONRES = _descriptor.Descriptor(
  name='DataComparisonRes',
  full_name='DataComparisonRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='DataComparisonRes.ret', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='DataComparisonRes.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res', full_name='DataComparisonRes.res', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=96,
)


_DATACOMPARISONPB = _descriptor.Descriptor(
  name='DataComparisonPB',
  full_name='DataComparisonPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_name', full_name='DataComparisonPB.table_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='DataComparisonPB.data', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=150,
)


_DATACOMPARISONREQ = _descriptor.Descriptor(
  name='DataComparisonReq',
  full_name='DataComparisonReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_id', full_name='DataComparisonReq.server_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='table_name', full_name='DataComparisonReq.table_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=210,
)

_DATACOMPARISONRES.fields_by_name['data'].message_type = _DATACOMPARISONPB
DESCRIPTOR.message_types_by_name['DataComparisonRes'] = _DATACOMPARISONRES
DESCRIPTOR.message_types_by_name['DataComparisonPB'] = _DATACOMPARISONPB
DESCRIPTOR.message_types_by_name['DataComparisonReq'] = _DATACOMPARISONREQ

DataComparisonRes = _reflection.GeneratedProtocolMessageType('DataComparisonRes', (_message.Message,), dict(
  DESCRIPTOR = _DATACOMPARISONRES,
  __module__ = 'proto_pb2'
  # @@protoc_insertion_point(class_scope:DataComparisonRes)
  ))
_sym_db.RegisterMessage(DataComparisonRes)

DataComparisonPB = _reflection.GeneratedProtocolMessageType('DataComparisonPB', (_message.Message,), dict(
  DESCRIPTOR = _DATACOMPARISONPB,
  __module__ = 'proto_pb2'
  # @@protoc_insertion_point(class_scope:DataComparisonPB)
  ))
_sym_db.RegisterMessage(DataComparisonPB)

DataComparisonReq = _reflection.GeneratedProtocolMessageType('DataComparisonReq', (_message.Message,), dict(
  DESCRIPTOR = _DATACOMPARISONREQ,
  __module__ = 'proto_pb2'
  # @@protoc_insertion_point(class_scope:DataComparisonReq)
  ))
_sym_db.RegisterMessage(DataComparisonReq)


# @@protoc_insertion_point(module_scope)
